export const FETCH_RECIPES = 'FETCH_RECIPES';
export const FETCHED_RECIPES = 'FETCHED_RECIPES';
export const NEXT_PAGE_RECIPES = 'NEXT_PAGE_RECIPES';
export const ERROR_RECIPES = 'ERROR_RECIPES';
export const FETCHED_RECIPE = 'FETCHED_RECIPE';
